# VaultDB Community - Docker Compose (Production)
# Uses published image from GitHub Container Registry

services:
  # ===========================================
  # Application
  # ===========================================

  app:
    image: ghcr.io/vaultdb-manager-backup/vaultdb-community:0.1.3
    container_name: vaultdb-app
    ports:
      - 4001:4000
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/vaultdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-change-me-in-production-32chars!}
      # Authentication (leave empty to disable)
      - AUTH_USERNAME=${AUTH_USERNAME:-}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-}
    volumes:
      - backups:/app/backups
      - restores:/app/restores
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3

  worker:
    image: ghcr.io/vaultdb-manager-backup/vaultdb-community:0.1.3
    container_name: vaultdb-worker
    command: ["node", "packages/server/dist/server/src/worker/main.js"]
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/vaultdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-change-me-in-production-32chars!}
      - BACKUP_CONCURRENCY=${BACKUP_CONCURRENCY:-2}
      - RESTORE_CONCURRENCY=${RESTORE_CONCURRENCY:-2}
    volumes:
      - backups:/app/backups
      - restores:/app/restores
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy
      app:
        condition: service_healthy
    restart: unless-stopped

  # ===========================================
  # Infrastructure
  # ===========================================

  mongo:
    image: mongo:7
    container_name: vaultdb-mongo
    environment:
      - MONGO_INITDB_DATABASE=vaultdb
    ports:
      - "${MONGO_PORT:-27018}:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: vaultdb-redis
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  backups:
  restores:

# ===========================================
# Usage
# ===========================================
#
# Start with default version (0.1.1):
#   docker compose -f .docker/prod/app.yaml up -d
#
# Start with specific version:
#   VERSION=1.0.0 docker compose -f .docker/prod/app.yaml up -d
#
# Start with authentication:
#   AUTH_USERNAME=admin AUTH_PASSWORD=secret docker compose -f .docker/prod/app.yaml up -d
#
# View logs:
#   docker compose -f .docker/prod/app.yaml logs -f
#
# Stop:
#   docker compose -f .docker/prod/app.yaml down
#
